### ISSUE TITLE
Link Broken

### ISSUE THREAD

**Issue by 4nc3str4l** [ElrondNetwork/elrond-proxy-go#108] opened 2020-12-03 19:57 UTC
Hello, the following link is broken on the README.md

**Comment by 4nc3str4l** [comment] 2020-12-03 19:57
![image](https://user-images.githubusercontent.com/6674976/101081326-3122aa80-35aa-11eb-8819-a818df130266.png)

**Comment by miiu96** [comment] 2020-12-07 10:57
Hello. Thank you for the feedback.
The problem is fixed now (https://github.com/ElrondNetwork/elrond-proxy-go/pull/110).

**Closed by miiu96** 2020-12-07 10:57 UTC
